### ISSUE TITLE
Default features not removed for feature test matrix

### ISSUE THREAD

**Issue by mdharm** [Person-93/cargo-feature-matrix#3]
Running `cargo feature-matrix` will produce output such as:
`running: cmd=test package=pkgname features=[]`
which indicates that no features are enabled.  However, this does not account for any features which are enabled by default in `Cargo.toml`.

Put another way, `Cargo.toml` contains:
```toml
[features]
default = [ "a" ]
a = []
b = []
```

Then `cargo feature-matrix test` will produce output indicating that the following configurations are tested:
```
running: cmd=test package=pkgname features=[]
running: cmd=test package=pkgname features=[a, b]
running: cmd=test package=pkgname features=[a]
running: cmd=test package=pkgname features=[b]
```

BUT, that is not correct.  All of the tests are run with feature `a` enabled, as it is the `default` feature.

This can be fixed by passing `--no-default-features` -- possibly only when a certain command-line argument is given of if a specific key is set in the `Cargo.toml` file.

I can fix this myself, if a PR would be accepted.  Let me know.

**Comment by Person-93** [comment]
Yes, I think the correct behavior would be to pass `--no-default-features` by default.

A PR would be appreciated.
