### ISSUE TITLE
Long delay for first output

### ISSUE THREAD

**Issue by mdharm** [Person-93/cargo-feature-matrix#4]
The output showing the command and configuration is printed using `print!()` before the command is executed.  However, on systems which are line-buffered, that output is not actually displayed until after a newline is printed -- which happens here when the results of the command are retrieved and the `OK` or `Fail` message is printed.  For projects that take several minutes to compile, this means that the operator gets no output until compilation is complete and the command is executed.

See [the rust documentation for `std::print`](https://doc.rust-lang.org/std/macro.print.html) for a discussion of this.

This could be fixed / improved by adding a call to `io::stdout().flush()` immediately after the first part of the status message is printed (before the command is executed) so that the output is immediately displayed.

I can fix this myself, if a PR would be accepted.  Let me know.

**Comment by Person-93** [comment]
> This could be fixed / improved by adding a call to io::stdout().flush() immediately after the first part of the status message is printed (before the command is executed) so that the output is immediately displayed.

This sounds good.

> I can fix this myself, if a PR would be accepted. Let me know.

This would be appreciated.
